### ISSUE TITLE
when deploying ARM template allow to select .parameters.json

### ISSUE THREAD

**Issue by rspaulino** [bradygaster-zz/azure-tools-vscode#45]
it would be nice if when in the same path there is multiple .parameters.json for example I could have a parameter file for dev, prod, QA been able to select which one I want to use with the azuredeploy.json

**Comment by bradygaster** [comment]
@rspaulino not a bad suggestion but at the moment we're sort of presuming the json file format in the github templates repo. that said, i don't object at all to this idea, as it'd give people the ability to create different environment files to use for multi-environment scenarios.
